In [1]:
import matplotlib
%matplotlib notebook

import os

In [2]:
root = os.path.realpath('H:/Can_cage/DeepCage_DLC_files')
config_path = os.path.join(root, 'DeepCageKeyTest-Can-2019-11-15/config.yaml')

## Visual

from deepcage.compute.test import (
    visualize_workflow,
    visualize_triangulation,
    visualize_basis_vectors,
    visualize_basis_vectors_single,
    plot_3d_trajectories
)

normalize = False

(fig_all, ax_all), (fig_sep, ax_sep) = plot_3d_trajectories(
    config_path, normalize=normalize, cm_is_real_idx=True, remap=True, cols=2, save=False
)

visualize_workflow(config_path, normalize=normalize, save=False)

visualize_basis_vectors(config_path, normalize=normalize, save=False)

visualize_basis_vectors_single(config_path, normalize=normalize, save=False)

## Analysis

In [3]:
from deepcage.auxiliary.detect import detect_triangulation_result
from deepcage.compute import (
    create_stereo_cam_origmap,
    compute_basis_vectors,
    dlc3d_create_labeled_video,
    map_experiment
)

C:\Users\Can\Miniconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Can\Miniconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Can\Miniconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Can\Miniconda3\envs\dlc\lib\site-packages\tensorflow\python\framework\dty

In [4]:
stereo_cam_units, orig_maps = create_stereo_cam_origmap(config_path)
coords = detect_triangulation_result(config_path, change_basis=True)

Calculating the basis vectors of NorthWest NorthEast
Attempting to fix coordinate-array by np.expand_dims(<array>, axis=1)

Cross product derived y-axis: [-0.3676315  -0.32128531 -0.87271005]
Origin-subtraction derived y-axis: [-0.21675097  0.67890148  0.7015068 ]
Angle between the two vectors: 138.64659482189393

Calculating the basis vectors of NorthEast EastNorth
Attempting to fix coordinate-array by np.expand_dims(<array>, axis=1)

Cross product derived y-axis: [-0.9448147  -0.18245529 -0.27209418]
Origin-subtraction derived y-axis: [ 0.25384646 -0.93275646 -0.25598313]
Angle between the two vectors: 90.0

Calculating the basis vectors of EastNorth EastSouth
Attempting to fix coordinate-array by np.expand_dims(<array>, axis=1)

Cross product derived x-axis: [ 0.53090433  0.10455306 -0.84095734]
Origin-subtraction derived x-axis: [ 0.08503818 -0.56989751  0.8173037 ]
Angle between the two vectors: 134.56797312187567

Calculating the basis vectors of SouthEast SouthWest
Attempting to

In [5]:
level1 = coords['level_1']

In [6]:
pair_ss = ('SouthEast', 'SouthWest')
pair_ss_info = orig_maps[pair_ss]
ss_coords = level1[pair_ss]

In [7]:
x, y, z = pair_ss_info['map'].T

In [8]:
from numpy.linalg import norm
print(norm(x), norm(y), norm(z))

1.0 1.0 1.0


In [9]:
pair_ss_info['axis_len']

2.3443069453906922e-15

In [10]:
ss_coords['tip']

array([[            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan

In [11]:
pair_ss_info['origin']

array([-1.55153995e-15, -1.85035388e-15,  4.91461554e-15])

In [14]:
(((ss_coords['tip'] - pair_ss_info['origin']) @ pair_ss_info['map']) / pair_ss_info['axis_len'])

array([[            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan,             nan],
       [            nan,             nan